wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.34
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.4
    session_history: code/_session_history.ipynb
